Repository fms-lab/julia-doc-ja, pull requests merged in 2021-01, with the labels that each got.

#47 Fix a bug in code-loading.md
  doc/src/manual/code-loading.md
Labels: bug

#48 Translation of handling operating system variation.md
  doc/src/manual/handling-operating-system-variation.md
Labels: documentation

#49 Add a workflow for code test triggerd by PR
  .github/workflows/codetest-workflow.yml
Labels: enhancement

#52 Fix parameters of show-versioninfo
  .github/workflows/codetest-workflow.yml
  .github/workflows/documentation-workflow.yml
Labels: bug

#51 Translation of integers and floating point numbers.md
  doc/src/manual/integers-and-floating-point-numbers.md
Labels: documentation
